import re
from playwright.sync_api import Page, expect, sync_playwright
import test_login



def test_commercial_account(page: Page):
    test_login.test_renegade_login(page)
    page.get_by_role("img", name="logo").first.click()
    page.get_by_role("heading", name="My Book").click()
    page.get_by_text("Accounts").first.click()
    page.wait_for_url("https://crm.dev.joinhobnob.com/mybook/accounts")
    page.get_by_role("button", name="Add account").click()
    page.get_by_role("button", name="Commercial").click()
    
    page.get_by_label("First name").click()
    page.get_by_label("First name").fill("sample")
    page.get_by_label("Last name*").click()
    page.get_by_label("Last name*").fill("k")
    page.locator("input[name=\"email\"]").click()
    page.locator("input[name=\"email\"]").fill("sample@hamon.in")
    page.get_by_role("textbox", name="Phone number*").click()
    page.get_by_role("textbox", name="Phone number*").fill("(234) 567-8478")
    page.locator(".date-input").click()
    page.get_by_role("option", name="Choose Monday, January 1st, 1990").click()
    page.locator(".css-15aalx3").click()
    page.locator("#react-select-11-option-0").click()
    page.locator("input[name=\"jurisdictionUUID\"]").click()
    page.locator("input[name=\"jurisdictionUUID\"]").fill("a")
    page.get_by_role("heading", name="Alabama").click()
    page.get_by_label("License number").click()
    page.get_by_label("License number").fill("890")
    page.get_by_label("Business name*").click()
    page.get_by_label("Business name*").fill("demo")
    page.get_by_label("Business phone number*").click()
    page.get_by_label("Business phone number*").fill("(234) 567-88764")
    page.get_by_label("Total payroll*").click()
    page.get_by_label("Total payroll*").fill("234")
    page.get_by_role("button", name="Save tick-sign").click()

def test_invalidcommercial_account(page: Page):
    test_login.test_renegade_login(page)
    page.get_by_role("img", name="logo").first.click()
    page.get_by_role("heading", name="My Book").click()
    page.get_by_text("Accounts").first.click()
    page.wait_for_url("https://crm.dev.joinhobnob.com/mybook/accounts")
    page.get_by_role("button", name="Add account").click()
    page.get_by_role("button", name="Commercial").click()

    page.get_by_label("First name").click()
    page.get_by_label("First name").fill("Sachin")
    page.locator(".date-input").click()
    page.get_by_role("option", name="Choose Tuesday, January 2nd, 1990").click()
    page.locator(".css-ackcql").click()
    page.locator("#react-select-11-option-0").click()
    page.locator("input[name=\"jurisdictionUUID\"]").click()
    page.locator("input[name=\"jurisdictionUUID\"]").fill("a")
    page.get_by_role("heading", name="Alabama").click()
    page.get_by_label("License number").dblclick()
    page.get_by_label("License number").fill("345")
    page.get_by_role("button", name="Save tick-sign").click()
    page.get_by_label("Last name*").click()
    page.get_by_text("Last name is required").click()
    page.get_by_role("textbox", name="Phone number*").click()
    page.get_by_text("Phone Number is required").click()
    page.locator("input[name=\"email\"]").click()
    page.get_by_text("Please enter your email").click()

def test_invalidbusiness_account(page: Page):
    test_login.test_renegade_login(page)
    page.get_by_role("img", name="logo").first.click()
    page.get_by_role("heading", name="My Book").click()
    page.get_by_text("Accounts").first.click()
    page.get_by_role("button", name="Add account").click()
    page.get_by_role("button", name="Commercial").click()
    page.get_by_label("First name").click()
    page.get_by_label("First name").fill("Sachin")
    page.get_by_label("Last name*").click()
    page.get_by_label("Last name*").fill("K")
    page.locator("input[name=\"email\"]").click()
    page.locator("input[name=\"email\"]").fill("Sachin12@hamon.in")
    page.get_by_role("textbox", name="Phone number*").click()
    page.get_by_role("textbox", name="Phone number*").fill("(234) 564-3855")
    page.locator(".date-input").click()
    page.get_by_role("option", name="Choose Tuesday, January 2nd, 1990").click()
    page.locator(".css-ackcql").click()
    page.locator("#react-select-11-option-0").click()
    page.locator("input[name=\"jurisdictionUUID\"]").click()
    page.locator("input[name=\"jurisdictionUUID\"]").fill("a")
    page.get_by_role("heading", name="Alabama").click()
    page.get_by_label("License number").click()
    page.get_by_label("License number").fill("345")
    page.get_by_role("button", name="Save tick-sign").click()
    page.get_by_label("Business name*").click()
    page.get_by_text("Please enter Business Name").click()
    page.get_by_label("Business phone number*").click()
    page.get_by_text("Please enter Business Phone Number").click()
    page.get_by_label("Total payroll*").click()
    page.get_by_text("Please enter Payroll").click()


   
